[window]
decorations = "Transparent"
blur = true
# opacity = 0.7
startup_mode = "Maximized"

title = "ROMANVIKI"
decorations_theme_variant = "Dark"


[font]
normal = { family = "FiraCode Nerd Font Mono", style = "Regular" }
bold = { family = "FiraCode Nerd Font Mono", style = "Bold" }
italic = { family = "FiraCode Nerd Font Mono", style = "Italic" }
bold_italic = { family = "FiraCode Nerd Font Mono", style = "Bold Italic" }


[env]
TERM = "xterm-256color"


